name: LiveKit Cloud Agents
description: Create, deploy, and manage LiveKit Cloud Agents
branding:
  icon: cloud
  color: purple
inputs:
  OPERATION:
    description: Operation to perform (create, deploy, status)
    required: true
    default: status
  WORKING_DIRECTORY:
    description: Which directory to run in
    required: false
    default: "."
  SLACK_TOKEN:
    description: Slack token for sending notifications
    required: false
  SLACK_CHANNEL:
    description: Slack channel to send notifications to (e.g., #general)
    required: false

runs:
  using: composite
  steps:
    - name: Run LiveKit Cloud Agent Operation
      shell: bash
      run: |
        docker run --rm \
          -e INPUT_OPERATION="${{ inputs.OPERATION }}" \
          -e INPUT_WORKING_DIRECTORY="${{ inputs.WORKING_DIRECTORY }}" \
          -e SLACK_TOKEN="${{ inputs.SLACK_TOKEN }}" \
          -e SLACK_CHANNEL="${{ inputs.SLACK_CHANNEL }}" \
          -e GITHUB_TOKEN="${{ github.token }}" \
          -e LIVEKIT_URL="${{ env.LIVEKIT_URL }}" \
          -e LIVEKIT_API_KEY="${{ env.LIVEKIT_API_KEY }}" \
          -e LIVEKIT_API_SECRET="${{ env.LIVEKIT_API_SECRET }}" \
          -e SECRET_LIST="${{ env.SECRET_LIST }}" \
          -v "${{ github.workspace }}:/workspace" \
          -w "/workspace" \
          docker.io/livekit/cloud-agents-github-plugin:v102
